### ISSUE TITLE
not skid

### ISSUE THREAD

**Issue by 6nz** [Syntheticc/Advanced-Anti-Debug#3]
https://github.com/Mickey758/Anti-Debug-Py
good job bro

**Comment by 6nz** [comment]
plus if ur using my list give credits
https://github.com/6nz/virustotal-vm-blacklist

**Comment by vepacoding** [comment]
> plus if ur using my list give credits https://github.com/6nz/virustotal-vm-blacklist

no

**Comment by 6nz** [comment]
Ok

**Comment by vepacoding** [comment]
> Ok

ok

**Comment by 6nz** [comment]
Literally no one asked ur opinion

**Comment by vepacoding** [comment]
> Literally no one asked ur opinion

ok

**Comment by HorridModz** [comment]
> 

https://docs.github.com/en/communities/maintaining-your-safety-on-github/reporting-abuse-or-spam

**Comment by Syntheticc** [comment]
> https://github.com/Mickey758/Anti-Debug-Py
> good job bro

never said i made it i said i put it together so how am i skid?

**Comment by HorridModz** [comment]
> > https://github.com/Mickey758/Anti-Debug-Py
> > good job bro
> 
> never said i made it i said i put it together so how am i skid?

Give credit or I'm reporting

**Comment by HorridModz** [comment]
Especially considering how your main goal looks like it is to get stars, so you are basically skidding someone else's program without credit for stars.

**Comment by 6nz** [comment]
> > https://github.com/Mickey758/Anti-Debug-Py
> > good job bro
> 
> never said i made it i said i put it together so how am i skid?

90% of the code is not urs

**Comment by Syntheticc** [comment]
> > > https://github.com/Mickey758/Anti-Debug-Py
> > > good job bro
> > 
> > 
> > never said i made it i said i put it together so how am i skid?
> 
> 90% of the code is not urs

keywords "put together" when did i say i coded it.....

**Comment by HorridModz** [comment]
> > > > https://github.com/Mickey758/Anti-Debug-Py
> > > > good job bro
> > > 
> > > 
> > > never said i made it i said i put it together so how am i skid?
> > 
> > 
> > 90% of the code is not urs
> 
> keywords "put together" when did i say i coded it.....

When did you say you didn't? You are required to give credit for reusing code. In fact, since the repository you took from came without a license, I'm pretty sure you are not allowed to use this at all, credit or not.
